//
//  LoginViewController.swift
//  BankApp
//
//  Created by Lynneker Souza on 5/29/20.
//  Copyright (c) 2020 Lynneker Souza. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginDisplayLogic: class {
    func displayUserAccountStatement(viewModel: Login.CreateLogin.ViewModel)
}

class LoginViewController: UIViewController, LoginDisplayLogic, UITextFieldDelegate {
    var interactor: LoginBusinessLogic?
    var router: (NSObjectProtocol & LoginRoutingLogic & LoginDataPassing)?
    
    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    
    private func setup() {
        let viewController = self
        let interactor = LoginInteractor()
        let presenter = LoginPresenter()
        let router = LoginRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: Routing
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        _ = userCompleteInformDada()
        loginTextField.delegate = self
        passwordTextField.delegate = self
    }
    
    // MARK: Text fields
    
    @IBOutlet weak var loginTextField: UITextField!
    @IBOutlet weak var passwordTextField: UITextField!
    
    func textFieldShouldReturn(_ textField: UITextField) -> Bool {        
        textField.resignFirstResponder()
        if textField == loginTextField {
            guard let user = loginTextField.text, !user.isEmpty else { return false }
            passwordTextField.becomeFirstResponder()
        } else if textField == passwordTextField {
            guard userCompleteInformDada() else { return false }
            passwordTextField.resignFirstResponder()
            createLogin()
        }
        return true
    }
    
    func textFieldDidEndEditing(_ textField: UITextField) {
        _ = userCompleteInformDada()
    }
    
    // MARK: Contact info
    
    func userCompleteInformDada() -> Bool {
        guard let user = loginTextField.text, !user.isEmpty,
        let password = passwordTextField.text, !password.isEmpty else {
            loginButton.alpha = 0.5
            loginButton.isEnabled = false
            return false
        }
        loginButton.alpha = 1.0
        loginButton.isEnabled = true
        return true
    }
    
    @IBOutlet weak var loginButton: UIButton!
    @IBAction func loginButtonTapped(_ sender: Any) {
        createLogin()
    }
    
    func createLogin() {
        guard let user = loginTextField.text, let password = passwordTextField.text, userCompleteInformDada() else { return }
        startLoadingAnimation()
        let request = Login.CreateLogin.Request(loginFromFields: Login.LoginFromFields(login: user, password: password))
        interactor?.createLogin(request: request)
    }
    
    func displayUserAccountStatement(viewModel: Login.CreateLogin.ViewModel) {
        stopLoadingAnimation()
        if viewModel.userAccount != nil {
            router?.routeToStatement(segue: nil)
        } else if let error = viewModel.error {
           displayError(viewModel: Login.CreateLogin.Response(userAccount: nil, error: error))
        }
    }
    
    // MARK: Error handling
    
    func displayError(viewModel: Login.CreateLogin.Response) {
        guard let error = viewModel.error else { return }
        let alertController = UIAlertController(title: "Ops", message: error.localizedDescription, preferredStyle: .alert)
        let alertAction = UIAlertAction(title: "OK", style: .default, handler: nil)
        alertController.addAction(alertAction)
        showDetailViewController(alertController, sender: nil)
    }
}
