//
//  ListStatementRouter.swift
//  BankApp
//
//  Created by Lynneker Souza on 5/29/20.
//  Copyright (c) 2020 Lynneker Souza. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ListStatementRoutingLogic {
  func routeBackToLogin()
}

protocol ListStatementDataPassing {
  var dataStore: ListStatementDataStore? { get }
}

class ListStatementRouter: NSObject, ListStatementRoutingLogic, ListStatementDataPassing {
  weak var viewController: ListStatementViewController?
  var dataStore: ListStatementDataStore?
  
  // MARK: Routing
    
    func routeBackToLogin() {
        guard let viewController = viewController else { return }
        navigateToLogin(source: viewController)
    }

  // MARK: Navigation
  
  func navigateToLogin(source: ListStatementViewController) {
    source.navigationController?.popViewController(animated: true)
  }
}
